import '../style/globals.css'
import { Metadata } from 'next'
import { Saira, Saira_Condensed } from 'next/font/google'

export const saira = Saira({ subsets: ['latin'] })
export const saira_condensed = Saira_Condensed({
  subsets: ['latin'],
  weight: ['100', '200', '300', '500', '600', '700', '800', '900']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={saira.className}>{children}</body>
    </html>
  )
}
