import saira from '@/utils/fonts/saira';
import '../style/globals.css'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={saira.className}>{children}</body>
    </html>
  )
}
